dataset:
  name: CIFAR10
  root: ./data/datasets
  batch_size: 256
  num_workers: 4
model:
  name: resnet18
  weights: ResNet18_Weights.DEFAULT
  num_classes: 10
preprocessing:
- name: to_tensor
loss:
  name: cross_entropy
optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0001
  scheduler: step
  step_size: 10
  gamma: 0.1
training:
  epochs: 1
  batch_size: 256
  num_workers: 4
  seed: 42
  device: cuda
scheduler:
  name: reduce_on_plateau
  patience: 1
  factor: 0.1
metrics:
- name: f1_score
  average: weighted
callbacks:
- name: checkpoint
  dirpath: checkpoints/
  monitor: Val_loss
  mode: min
- name: wandb_logger
  project: deteccion_malware_con_dl
  entity: dap1013-universidad-de-burgos
output_logger:
  name: wandb_img_output_errors
experiment_id: resnet18_b7601abd
