_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.9.12
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
callbacks:
    value:
        - dirpath: checkpoints/
          mode: min
          monitor: Val_loss
          name: checkpoint
        - entity: dap1013-universidad-de-burgos
          name: wandb_logger
          project: deteccion_malware_con_dl
dataset:
    value:
        batch_size: 256
        name: hackathon
        num_workers: 4
        root: ./data/datasets
experiment_id:
    value: base_model_870db63b
loss:
    value:
        name: cross_entropy
metrics:
    value:
        - average: weighted
          name: f1_score
model:
    value:
        input_size: 51
        name: base_model
        num_classes: 4
optimizer:
    value:
        gamma: 0.1
        lr: 0.001
        name: adam
        scheduler: step
        step_size: 10
        weight_decay: 0.0001
output_logger:
    value:
        name: wandb_img_output_errors
preprocessing:
    value:
        - name: to_tensor
scheduler:
    value:
        factor: 0.1
        name: reduce_on_plateau
        patience: 1
training:
    value:
        batch_size: 256
        device: cuda
        epochs: 4
        num_workers: 4
        seed: 42
